import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export async function getServerSideProps() {
  console.log(process.env.PRIVATE_API_KEY)

  return {
    props: {
      hello: 'world'
    }
  }
}

const Home: NextPage = () => {

  const uploadFunc = (e: any) => {
    e.preventDefault()
    console.log(e)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Amazon AWS S3 integration</h1>
        <button
          onClick={uploadFunc}>Upload</button>

      </main>
    </div>
  )
}

export default Home

